# Generated by Django 3.2.16 on 2024-02-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20240222_1625'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_unique_constraint',
        ),
    ]
